---
# Playbook for installing Hyrax IR Stack.

- name: Install Hyrax on local hosts.
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  roles:
    - hyrax
  environment:
    MAKEFLAGS: '-j {{ make_jobs }}'
