---
# Install Ruby

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - patch
    - curl
    - bzip2
    - tar
    - make

- name: Download ruby-install tarball
  get_url:
    url: "https://github.com/postmodern/ruby-install/archive/v{{ ruby_install_version }}.tar.gz"
    dest: "/tmp/ruby-install-{{ ruby_install_version }}.tar.gz"
    owner: root
    group: root
    mode: u=r,g=r,o=
    checksum: "{{ ruby_install_checksum }}"

- name: Unarchive ruby-install into temp directory
  unarchive:
    remote_src: yes
    src: "/tmp/ruby-install-{{ ruby_install_version }}.tar.gz"
    dest: /tmp
    creates: "/tmp/ruby-install-{{ ruby_install_version }}"

- name: Install ruby-install
  command: make install
  args:
    chdir: "/tmp/ruby-install-{{ ruby_install_version }}"
    creates: /usr/local/bin/ruby-install

- name: Install ruby
  command: /usr/local/bin/ruby-install ruby --system {{ ruby_version }} --sha256 {{ ruby_tarbz2_sha256_checksum }}
  args:
    creates: /usr/local/bin/ruby

- name: Add ruby installation directory to sudo path
  copy:
    src: addusrlocalbintopath
    dest: /etc/sudoers.d/addusrlocalbintopath
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
